# Generated by Django 4.2.3 on 2023-07-17 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='hire',
            new_name='hire_date',
        ),
    ]
